### ISSUE TITLE
Update successful but values outdated

### ISSUE THREAD

**Issue by chriscatuk** [DasBasti/SmartHashtag#163]
## Version of the custom_component

0.5.0

## Configuration

changed all updates to 60s for testing purpose. 

## Describe the bug

After working perfectly during charging or driving, regularly the last data stay shown instead of showing the charging stopped or driving stopped.

For example: I see charging power to 6800W even if I know it stopped. Last update is also stuck in the past and all values.

In those cases, I reload the integration and it updates correctly the values again.

When the data are frozen to outdated values, we are still seeing logs as if all is ok:

On Hello # we see clearly the values are updated on the API response. It's the HA integration that is not updating the values.

## Debug log

```
2024-08-27 19:11:30.620 DEBUG (MainThread) [custom_components.smarthashtag] Finished fetching smarthashtag data in 1.118 seconds (success: True)
2024-08-27 19:12:00.202 INFO (MainThread) [custom_components.smarthashtag] Updatefrequency set for climate: 0:01:00
2024-08-27 19:12:31.667 DEBUG (MainThread) [custom_components.smarthashtag] Finished fetching smarthashtag data in 1.165 seconds (success: True)
2024-08-27 19:13:00.202 INFO (MainThread) [custom_components.smarthashtag] Updatefrequency set for climate: 0:01:00
```

**Comment by chriscatuk** [comment]
I can't be sure it's related as I didn't get the error in the afternoon when it froze. But tonight I see an error I already saw this morning. 

I have multiple cars linked to my account. 

```
This error originated from a custom integration.

Logger: custom_components.smarthashtag
Source: helpers/update_coordinator.py:354
integration: Smart (documentation, issues)
First occurred: 27 August 2024 at 08:18:54 (2 occurrences)
Last logged: 27 August 2024 at 23:40:29

Unexpected error fetching smarthashtag data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 354, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/smarthashtag/coordinator.py", line 44, in _async_update_data
    return await self.account.get_vehicles()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pysmarthashtag/account.py", line 111, in get_vehicles
    vehicle_info = await self.get_vehicle_information(vin)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pysmarthashtag/account.py", line 164, in get_vehicle_information
    r_car_info = await client.get(
                 ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/httpx/_client.py", line 1801, in get
    return await self.request(
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/httpx/_client.py", line 1574, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/httpx/_client.py", line 1661, in send
    response = await self._send_handling_auth(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/httpx/_client.py", line 1689, in _send_handling_auth
    response = await self._send_handling_redirects(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/httpx/_client.py", line 1747, in _send_handling_redirects
    raise exc
  File "/usr/local/lib/python3.12/site-packages/httpx/_client.py", line 1729, in _send_handling_redirects
    await hook(response)
  File "/usr/local/lib/python3.12/site-packages/pysmarthashtag/api/client.py", line 92, in raise_for_status_event_handler
    raise httpx.HTTPStatusError(
httpx.HTTPStatusError: 4038: Current vehicle is not in use
```

**Comment by chriscatuk** [comment]
when I try to start the air conditioning, I get the error:

```
Failed to perform the action climate/set_hvac_mode. 4038: Current vehicle is not in use
```

it might be what was causing the (unrelated) log from above

**Comment by DasBasti** [comment]
Yeah it feels like the whole API is a little bit unstable today. I tried to debug and was not able to log into my account every time. Sometime it works sometime it doesn't. Also sometimes I got that error
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 364, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/smarthashtag/device_tracker.py", line 20, in async_setup_entry
    [SmartVehicleLocation(coordinator, vehicle)], update_before_add=True
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/smarthashtag/device_tracker.py", line 41, in __init__
    super().__init__(coordinator)
  File "/config/custom_components/smarthashtag/entity.py", line 23, in __init__
    self._attr_unique_id = coordinator.config_entry.entry_id
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'entry_id'

**Comment by DasBasti** [comment]
Reloading the entity seems to help

**Comment by chriscatuk** [comment]
It was easy to reproduce the issue for a couple of days.  But today it worked without problem.

**Comment by DasBasti** [comment]
I found that the coordinator config_entry sometimes is not set. But I do not know why. I put some logging into my local instance and now I have to wait for it to happen again. I did not achieve it by activating climate preconditioning. So might take a little time to get more information on the issue.

**Comment by chriscatuk** [comment]
most of the times I could see the data frozen when charging stopped.   I could still see the latest charging happening in HA, but not in Hello # where it was correctly showing as finished.

I think preconditioning is a different issue, in my case it would be related to having more than one car.
